# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20171021_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='check_out_date',
        ),
    ]
